Fix Chromatic TurboSnap
`frontend:chromatic` started failing on another branch because TurboSnap
wasn't working. I think when I set it up originally I didn't see the
issue because TurboSnap is skipped when there are changes to
`package.json`, so it didn't even try running and thus didn't fail:

```
⚠ TurboSnap disabled due to file change
Found a dependency change in projects/frontend/package.json
```

However in other branches where there are not changes to `package.json`,
TurboSnap wasn't skipped and it tried to run and would fail:

```
Error: ✖ Failed to publish your built Storybook
✖ TurboSnap disabled due to missing stats file
Did not find preview-stats.json in your built Storybook.
Make sure you pass --webpack-stats-json when building your Storybook.
    at yfi (/home/runner/work/haohao.how/haohao.how/node_modules/chromatic/dist/chunk-KVYFOQS5.js:1346:1068)
    at xW.task (/home/runner/work/haohao.how/haohao.how/node_modules/chromatic/dist/chunk-KVYFOQS5.js:617:24602)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```